# Generated by Django 4.1 on 2022-08-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=5)),
                ('emailId', models.EmailField(max_length=254)),
                ('companyCode', models.CharField(max_length=5)),
                ('Strength', models.IntegerField()),
                ('website', models.URLField()),
                ('created_time', models.DateTimeField()),
            ],
        ),
    ]
