# Generated by Django 4.1 on 2022-08-15 08:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Strength',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyCode',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2}\\[0-9]{1,2}\\[E,N]$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.TextField(max_length=120, validators=[django.core.validators.MinLengthValidator(5, 'the filed must contain at least 5 char')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 8, 28, 3, 822326, tzinfo=datetime.timezone.utc)),
        ),
    ]
